### ISSUE TITLE
get-pip.py tries to download a file after installation - Proxy configuration is not used

### ISSUE THREAD

**Issue by jcralbino** [pypa/get-pip#108]
I am using the get-pip.py but i am uniable to make it work via Proxy. 
The error is 

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001E3DF47C1C0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pip/
ERROR: Could not find a version that satisfies the requirement pip
ERROR: No matching distribution found for pip

Can we :
- Define a option for setting up proxy connection when launching?
- My understanding is that this script includes a data payload.

**Comment by pradyunsg** [comment]
This script effectively does `pip install pip` (at least, in an environment that doesn't contain pip).

While it does have a payload that's theoretically good-enough to be installed, this script is intended to get you the latest version of pip when run. This needs network access, so you'd need to configure the proxy server so that this script is able to install pip. Your other option is to use ensurepip that ships with your Python installation (I'm assuming you're not on an unsupported Python version).

**Comment by pradyunsg** [comment]
You can set http_proxy (or https_proxy, depending on which kind you have); or pass --proxy to `get-pip.py`.

**Comment by jcralbino** [comment]
So Altough the data payload is there in practice is not used, as it will prefer the online version? If no internet access is available the installation is not done ?

**Comment by pradyunsg** [comment]
Yup.

https://github.com/pypa/get-pip/blob/5a43acd2179f77d4e6385aa766cc7d7542d2eff7/templates/default.py#L84

We literally run `pip install --upgrade` to perform the installation, which expects that it can find distributions of pip. Note that it's also possible to add --no-index and combine it with --find-links etc, but I don't know anyone who's doing that.

**Comment by xavfernandez** [comment]
I think all questions were answered :)
