### ISSUE TITLE
get-pip.py hosting: access control and malicious actor mitigation

### ISSUE THREAD

**Issue by andrewegel** [pypa/get-pip#110]
This issue isn't about any malware I have found, and I'm (hopefully) opening an inquiry into the most relevant issues board around the hosting of `https://bootstrap.pypa.io/get-pip.py` - Please direct me to a more applicable project / issue type if this is not the correct place.

A little Background:

The codecov breach has had some farther reaching impacts - You can read the company's response here: https://about.codecov.io/security-update/

And you can likely find more information about it with 1 minute of googling things. The TL;DR is that you can use curl with bash to integrate with their service: https://docs.codecov.io/docs/about-the-codecov-bash-uploader

Like so:

```
bash <(curl -s https://codecov.io/bash)
```

Not withstanding comments around "executing things off the internet is never a good idea" - the idea is the same for getting pip: https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
```

This is all fine and dandy, but the content at `https://codecov.io/bash` was replaced with a malicious script that grabbed shell environment variables (Mainly Build-time secrets) and sent them to an attacker for secret harvesting.

Therefore as a "concerned OSS citizen", what:
* Assurances are in place that the content under `bootstrap.pypa.io` has the proper access controls to prevent a malicious actor from replacing the content of the `get-pip.py` document with malicious code.
* What steps can be taken for end-users to validate that what they get from `bootstrap.pypa.io` is correct.

In general I'm going to take steps to replace instances of `curl https://bootstrap.pypa.io/get-pip.py` with something more secure, but as responsible OSS citizens whats PyPa's response to this incident in the context of their own systems?

**Comment by andrewegel** [comment]
Appologies for replying late here - I've actually had to do my own hose keeping / auditing around the CodeCov issue mentioned.

So I understand the access controls after:

> The contents of bootstrap.pypa.io will mirror what's in the public/ directory of this project, gotten via a git pull -- so that's about as secure as a well managed web server.

However its up to this point that I'm concerned the most about. What is "serving" things here? A VM thats fronted by a CDN? This is conjecture from me looking at:

https://github.com/python/psf-salt/tree/master/salt/pypa/bootstrap

As I assume (Not a salt stack expert) that this is some "generic" Linux system. Which is where I'm most concerned:

* What access controls are in place for this system?
* Are regular audits performed?
* What OS is this system running? Are you regularly patching it?

My concern is that an attacker gets access to this system they can replace the content served to your users. I can't speak to how CodeCov got "owned" but the crux of it is that CodeCov wasn't auditing the changes, and an external user reported that their bash script was no longer matching the expected checksum.

> I'm not sure there's ever a "PyPA response" to anything, because PyPA is a very loosely bound group of volunteers.

I understand - I would therefore propose to be "good citizens" in the OSS world that you deprecate anything involving boostrap/get-pip in everything pip (Documentation, etc) if you can't adequately audit, monitor and ensure that you're not serving a malicious payload.

**Comment by ewdurbin** [comment]
Hi @andrewegel! you raise some great questions about the PSF infrastructure that backs much of python.org, pypi.org, and pypa.io.

We are currently running the latest Ubuntu 18.04 LTS, patched nightly with unattended-upgrades, and a hardened SSH configuration for all hosts in the infra. Each host is limited to the minimum set of users necessary to fulfill their roles as volunteer admins of any given service. Our logins are logged locally and broadcast back to our salt server. 99% of regular maintenance is done without login and is automated by the salt infrastructure. Changes to our core infrastructure are gated by manual deploy (i.e. someone couldn't replace what repo get-pip is served from without manual intervention by one of three users with access to the salt server).

I understand you are frustrated with the burden that you took on due to the CodeCov issue, but I'm concerned that you are misdirecting much of that anger toward this project in your presumptions and demands.

Please try to bring your comments back to a more positive, encouraging, and curious demeanor. The core of what you are saying is valid, but the manner in which you presented it was apparently striking enough that someone mentioned to me saying "I'm not sure how to diplomatically respond to this." That's not the environment we want to foster here with in the PyPA, Python Community, or Open Source at large.

**Comment by andrewegel** [comment]
Apologies if my tone seemed demanding or presumptuous - In retrospect I should have dug deeper and found [1] as indicators of steps taken to harden the security around whats serving things here. Your answer around users/admins also fills in some of those gaps. 

I'll put my support behind a https://github.com/pypa/get-pip/issues/41 feature, I would hate to see a CodeCov or PHPPear like incident happen to PyPA.

My questions are answered & I'm satisfied so I will close this issue as its probably a dupe to https://github.com/pypa/get-pip/issues/41. Please disregard my comments about deprecating boostrap/get-pip.

[1] https://github.com/python/psf-salt/tree/master/salt/base/harden
