### ISSUE TITLE
use of mmap

### ISSUE THREAD

**Issue by verhulstm** [pypa/get-pip#153]
hi, i have a question

issue with -- with rustpython --install-pip 

https://github.com/RustPython/RustPython/issues/3670

why does get-pip need mmap? 

might you be able to add a option?

python get-pip.py --no-mmap?

i want to get pip working with rustpytohn again

thanks

**Comment by pradyunsg** [comment]
`pip` is using CacheControl, for interacting with its cache. IIUC, the import of mmap is happening in that project: https://github.com/ionrock/cachecontrol/blob/139cd4e34ff0b59a14b94090e6fc6e004750fb22/cachecontrol/filewrapper.py#L6

Please file an issue with github.com/ionrock/cachecontrol (ideally with a PR since the maintainer has limited availability, IIUC).
