### ISSUE TITLE
No module named 'apt_pkg' running get-pip.py python3.8

### ISSUE THREAD

**Issue by bradleysawler** [pypa/get-pip#64]
Resolved per [askubuntu](https://askubuntu.com/a/1222656): 
```
cd /usr/lib/python3/dist-packages
# where 36m is the file you have
sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so

**Comment by liran319** [comment]
> Resolved per [askubuntu](https://askubuntu.com/a/1222656):
> 
> ```
> cd /usr/lib/python3/dist-packages
> # where 36m is the file you have
> sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so
> ```

It works for me! Thanks!

**Comment by pradyunsg** [comment]
Thanks! Closing since there's nothing actionable for us here, and this seems to be something specific to Debian/Ubuntu. Please contact the Debian maintainers via their issue reporting mechanisms to tell them about this issue.

/cc @doko42 @kitterma I believe this is rendering get-pip.py unusable on Ubuntu.

**Comment by webknjaz** [comment]
Is this an instance of https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e ?

**Comment by pradyunsg** [comment]
Maybe? I'm not gonna look into that right now. 🤷🏽
