### ISSUE TITLE
Install pip without distutils package

### ISSUE THREAD

**Issue by cserpell** [pypa/get-pip#96]
In summary: Ubuntu without `distutils` package installed. Is there any way to install pip there *without root access*?

I looked on other issues, and most recommend installing the Ubuntu package with `sudo`, which is impossible in my case.

**Comment by webknjaz** [comment]
It's highly discouraged to affect your system pip install (like with `sudo`) as it will conflict with what apt installs and tracks (not even talking about countless ways to break your system or Python experience — https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e).

It's probably best to just use virtualenv that gets you some version of pip that you can then upgrade just for that virtualenv. Personally, I also prefer using userspace Python installs managed via `pyenv` so that I don't mess up anything in the OS, it also doesn't need root and you can have as many Pythons as you want.

Also, `distutils` is a part of the official CPython distribution, it's Ubuntu/Debian problem that they break this promise, their Python may be missing parts by default so you'll have to follow their recommendations, there's nothing PyPA can do about that.

**Comment by pradyunsg** [comment]
Closing since there's nothing actionable for us here. :)
